version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shesawlabs_postgres
    environment:
      - POSTGRES_DB=shesawlabs_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

  app:
    build: .
    container_name: shesawlabs_app
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
