version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: shesaw_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shesaw_network

  # 메인 애플리케이션
  app:
    build: .
    container_name: shesaw
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - shesaw_network
    command: ["python", "main.py", "--test"]

  # 개발용 환경
  dev:
    build: .
    container_name: shesaw_dev
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - shesaw_network
    command: ["tail", "-f", "/dev/null"]
    profiles:
      - dev

volumes:
  postgres_data:

networks:
  shesaw_network:
    driver: bridge
