-- Mock Reviews 데이터 생성 스크립트
-- review 테이블에 다양한 사용자의 리뷰 데이터를 생성합니다

INSERT INTO reviews (
  id, user_id, review_text, location, time_of_day, rating, 
  selected_keywords, recommended_keywords, score_result, 
  context_analysis, analysis_method
) VALUES 
(
  gen_random_uuid()::text,
  1,
  '역삼역 근처인데 사람도 많고 가로등도 잘 되어있어서 밤에도 안전해요. CCTV도 많이 보이고 경찰서도 가까워서 마음이 놓여요.',
  '강남구 역삼동',
  '밤',
  5,
  '[{"category": "자연적 감시", "keyword": "밝음"}, {"category": "자연적 감시", "keyword": "CCTV많음"}, {"category": "활동 활성화", "keyword": "사람많음"}, {"category": "감정형", "keyword": "안심"}]'::jsonb,
  '[{"category": "자연적 감시", "keyword": "가로등", "confidence": 0.9, "reason": "가로등도 잘 되어있어서"}, {"category": "자연적 감시", "keyword": "CCTV", "confidence": 0.8, "reason": "CCTV도 많이 보이고"}]'::jsonb,
  '{"totalScore": 85, "safetyLevel": "안전", "categoryScores": {"naturalSurveillance": 35, "activitySupport": 25, "emotional": 25}, "recommendations": ["현재 안전 상태가 양호합니다."]}'::jsonb,
  '{"emotionalSummary": "매우 안전하고 안심되는 분위기", "situationSummary": "밤시간 대중교통 이용 시 안전한 환경"}'::jsonb,
  'gpt'
),
(
  gen_random_uuid()::text,
  2,
  '홍대 근처는 사람이 너무 많고 복잡해서 약간 불안하긴 하지만 그래도 밝고 활기차서 나쁘지 않아요.',
  '마포구 홍대동',
  '저녁',
  3,
  '[{"category": "활동 활성화", "keyword": "사람많음"}, {"category": "자연적 접근 통제", "keyword": "복잡"}, {"category": "자연적 감시", "keyword": "밝음"}, {"category": "감정형", "keyword": "약간불안"}]'::jsonb,
  '[{"category": "활동 활성화", "keyword": "상업지역", "confidence": 0.8, "reason": "홍대 상업지역 특성"}]'::jsonb,
  '{"totalScore": 15, "safetyLevel": "보통", "categoryScores": {"activitySupport": 20, "accessControl": -10, "naturalSurveillance": 15, "emotional": -10}, "recommendations": ["접근 통제 시설 보완이 필요합니다."]}'::jsonb,
  '{"emotionalSummary": "복잡하지만 활기찬 분위기", "situationSummary": "저녁시간 상업지역의 혼잡함"}'::jsonb,
  'gpt'
),
(
  gen_random_uuid()::text,
  3,
  '대학가 근처 주택가인데 조용하고 좋긴 한데 가로등이 좀 부족한 것 같아요. 밤에는 좀 어두워서 무서울 때가 있어요.',
  '관악구 낙성대동',
  '밤',
  2,
  '[{"category": "자연적 감시", "keyword": "어두움"}, {"category": "환경 정비", "keyword": "조용함"}, {"category": "감정형", "keyword": "불안"}]'::jsonb,
  '[{"category": "자연적 감시", "keyword": "가로등부족", "confidence": 0.85, "reason": "가로등이 좀 부족한"}]'::jsonb,
  '{"totalScore": -20, "safetyLevel": "주의", "categoryScores": {"naturalSurveillance": -25, "maintenance": 5, "emotional": -15}, "recommendations": ["조명 개선이 필요합니다."]}'::jsonb,
  '{"emotionalSummary": "조용하지만 어두워서 불안", "situationSummary": "밤시간 주거지역의 조명 부족"}'::jsonb,
  'gpt'
),
(
  gen_random_uuid()::text,
  NULL,
  '새벽에 편의점 가는 길인데 가로등이 고장난 곳이 몇 군데 있어서 무서웠어요.',
  '노원구 상계동',
  '새벽',
  2,
  '[{"category": "자연적 감시", "keyword": "어두움"}, {"category": "환경 정비", "keyword": "시설고장"}, {"category": "감정형", "keyword": "불안"}]'::jsonb,
  '[{"category": "자연적 감시", "keyword": "가로등고장", "confidence": 0.9, "reason": "가로등이 고장난 곳이"}]'::jsonb,
  '{"totalScore": -35, "safetyLevel": "위험", "categoryScores": {"naturalSurveillance": -25, "maintenance": -15, "emotional": -15}, "recommendations": ["조명 개선이 필요합니다.", "환경 정리 및 관리가 필요합니다."]}'::jsonb,
  '{"emotionalSummary": "어둡고 불안한 분위기", "situationSummary": "새벽시간 시설 고장으로 인한 위험"}'::jsonb,
  'gpt'
),
(
  gen_random_uuid()::text,
  NULL,
  '공원이 있어서 운동하는 사람들도 많고 벤치도 많아서 쉬기 좋아요. CCTV도 보이고 관리가 잘 되어있는 것 같아요.',
  '송파구 석촌동',
  '오후',
  4,
  '[{"category": "활동 활성화", "keyword": "공원있음"}, {"category": "자연적 감시", "keyword": "CCTV많음"}, {"category": "환경 정비", "keyword": "깨끗함"}, {"category": "감정형", "keyword": "안심"}]'::jsonb,
  '[{"category": "활동 활성화", "keyword": "운동시설", "confidence": 0.8, "reason": "운동하는 사람들도 많고"}]'::jsonb,
  '{"totalScore": 75, "safetyLevel": "안전", "categoryScores": {"activitySupport": 30, "naturalSurveillance": 25, "maintenance": 20}, "recommendations": ["현재 안전 상태가 양호합니다."]}'::jsonb,
  '{"emotionalSummary": "활기차고 잘 관리된 공원", "situationSummary": "오후시간 공원의 활발한 이용"}'::jsonb,
  'gpt'
),
(
  gen_random_uuid()::text,
  1,
  '',
  '송파구 잠실동',
  '오후',
  4,
  '[{"category": "자연적 감시", "keyword": "밝음"}, {"category": "활동 활성화", "keyword": "공원있음"}, {"category": "자연적 감시", "keyword": "CCTV많음"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": 55, "safetyLevel": "안전", "categoryScores": {"naturalSurveillance": 30, "activitySupport": 25}, "recommendations": ["현재 안전 상태가 양호합니다."]}'::jsonb,
  '{"keywordSelectionMethod": "manual_only"}'::jsonb,
  'keywords_only'
),
(
  gen_random_uuid()::text,
  2,
  '',
  '영등포구 여의도동',
  '저녁',
  3,
  '[{"category": "자연적 감시", "keyword": "CCTV많음"}, {"category": "활동 활성화", "keyword": "사람많음"}, {"category": "환경 정비", "keyword": "깨끗함"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": 45, "safetyLevel": "보통", "categoryScores": {"naturalSurveillance": 20, "activitySupport": 15, "maintenance": 10}, "recommendations": ["현재 안전 상태가 양호합니다."]}'::jsonb,
  '{"keywordSelectionMethod": "manual_only"}'::jsonb,
  'keywords_only'
),
(
  gen_random_uuid()::text,
  3,
  '지하철역 근처인데 출구가 많고 사람도 많아서 안전해 보여요. 하지만 골목으로 들어가면 좀 어두워져요.',
  '용산구 이태원동',
  '저녁',
  3,
  '[{"category": "자연적 접근 통제", "keyword": "출구많음"}, {"category": "활동 활성화", "keyword": "사람많음"}, {"category": "자연적 감시", "keyword": "어두움"}]'::jsonb,
  '[{"category": "자연적 감시", "keyword": "어두운골목", "confidence": 0.8, "reason": "골목으로 들어가면 좀 어두워져요"}, {"category": "활동 활성화", "keyword": "지하철역", "confidence": 0.9, "reason": "지하철역 근처"}]'::jsonb,
  '{"totalScore": 5, "safetyLevel": "보통", "categoryScores": {"accessControl": 10, "activitySupport": 15, "naturalSurveillance": -20}, "recommendations": ["조명 개선이 필요합니다."]}'::jsonb,
  '{"locationContext": "이태원 상업지역", "timeContext": "저녁시간 유동인구 많음", "riskAssessment": "골목 지역 조명 부족"}'::jsonb,
  'restricted'
),
(
  gen_random_uuid()::text,
  4,
  '편의점이 24시간이라 안전해요',
  '강남구 신사동',
  '밤',
  4,
  '[{"category": "활동 활성화", "keyword": "편의점"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": 30, "safetyLevel": "보통"}'::jsonb,
  '{}'::jsonb,
  'restricted'
),
(
  gen_random_uuid()::text,
  5,
  '공원이 잘 관리되어있어요',
  '서초구 반포동',
  '오후',
  5,
  '[{"category": "환경 정비", "keyword": "깨끗함"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": 40, "safetyLevel": "보통"}'::jsonb,
  '{}'::jsonb,
  'restricted'
),
(
  gen_random_uuid()::text,
  6,
  '골목이 복잡해서 길을 잃을 뻔했어요',
  '마포구 합정동',
  '저녁',
  2,
  '[{"category": "자연적 접근 통제", "keyword": "복잡"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": -15, "safetyLevel": "주의"}'::jsonb,
  '{}'::jsonb,
  'restricted'
),
(
  gen_random_uuid()::text,
  NULL,
  '주차장이 어두워서 무서워요',
  '서대문구 신촌동',
  '밤',
  2,
  '[{"category": "자연적 감시", "keyword": "어두움"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": -25, "safetyLevel": "주의"}'::jsonb,
  '{}'::jsonb,
  'restricted'
),
(
  gen_random_uuid()::text,
  NULL,
  '상점가라서 밝고 안전해요',
  '양천구 목동',
  '저녁',
  5,
  '[{"category": "자연적 감시", "keyword": "밝음"}]'::jsonb,
  '[]'::jsonb,
  '{"totalScore": 40, "safetyLevel": "보통"}'::jsonb,
  '{}'::jsonb,
  'gpt'
);